# Generated by Django 2.0.2 on 2018-07-18 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0003_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Age',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
