# Generated by Django 2.0.2 on 2018-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0004_auto_20180718_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
