# Generated by Django 2.0.5 on 2018-07-18 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0005_auto_20180718_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
