# Generated by Django 2.0.5 on 2018-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0006_city_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
