# Generated by Django 2.0.2 on 2018-07-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0007_auto_20180718_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User Data'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='Date',
        ),
    ]
